---
title: "Practical Machine Learning: readme"
author: "Marcio Lopes"
date: "31 January 2016"
output: html_document
---

This project uses data from devices such as Jawbone Up, Nike FuelBand, and Fitbit. Six participants were asked to perform barbell lifts correctly and incorrectly in 5 different ways. The method in which the exercise was performed was labelled `classe` and was stored as a factor variable with levels A through E. In this project, I use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants to predict `classe`. This has interesting applications, since in future it would be possible to alert participants if they are doing exercises incorrectly, and thus prevent back damage.

The `project.R` file contains all the code needed to build a classtification tree and a random forest to predict `classe`. `Report.Rmd` is a walkthrough to (most) of the code in `project.R`. It details the steps and theory as well as provides explanations for the parameters used in the models. `Report.html` is `Report.Rmd` compiled into a friendlier html format.